name: "Deploy to GitHub"

on:
  push:
     tags:
        - "*" 
           
env:
   PROJECT_PATH: WordsPy/WordsPy
    
jobs:
  deploy:
     steps:
        - uses: actions/create-release@v1
          id: create_release
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
            tag_name: ${{ github.ref }} 
            release_name: ${{ github.ref }}